Algoritmo "semnome"


procedimento ola(nome:caractere)
Var

Inicio
    escreval("ola ",nome," mundo procedimento")
fimprocedimento

procedimento ola2(qtd:inteiro)
Var
  cont:inteiro
  nome2:caractere


Inicio

  para cont de 1 ate qtd passo 1 faca
     leia(nome2)
     escreval("boa noite",nome2)
  fimpara

fimprocedimento


Var



Inicio


    ola("lucas")
    ola2(5)


Fimalgoritmo